services:
#    mosaika_rad.example:
#        class: Mosaika\RadBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    rad.factory:
        class: Mosaika\RadBundle\Factory\RadFactory
        arguments: ["@service_container"]